%% Define seeds (sheet names)
seeds = {'LCP2',...
'THBS2',...
'BUB1',...
'CD53',...
'COL5A1',...
'KIF4A',...
'TYROBP',...
'FBN1',...
'BUB1B',...
'LAPTM5',...
'ANTXR1',...
'BUB1_2',...
'PTPRC',...
'COL5A2',...
'CENPA',...
'CD5',...
'GLT8D2',...
'TPX2'};

%% Read excel file
num_attractors = numel(seeds);
attractors = cell(num_attractors,1);
for i = 1:num_attractors
    [junk,attractors{i}] = xlsread('Attractors.xlsx',['seed=' seeds{i}]);
    attractors{i}{51,1} = '012345678901234';
    attractors{i}{51,2} = '012345678901234';
end

%% Evaluate attractors
score = zeros(num_attractors,1);
max_score = 50;
for k = 1:num_attractors
    C1 = char(attractors{k}{:,1});
    C2 = char(attractors{k}{:,2});
    for i = 1:50
        for n = 1:50
            if C1(i,:) == C2(n,:)
                score(k) = score(k) + 1;
            end
        end
    end
end

score_norm = score/max_score;
%result = 72% accuracy in getting the right attractor (top 50 genes) given seed gene,
%ignoring ordering